// ═══════════════════════════════════════════════════════════════
// NEXUS — A2UI Renderer
// Renders dynamic cards generated by agents (forms, charts, tables)
// ═══════════════════════════════════════════════════════════════

"use client";

import { useState, useCallback } from "react";
import { motion } from "framer-motion";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  BarChart3,
  Table2,
  FileCode,
  FormInput,
  AlertCircle,
  CheckCircle,
  AlertTriangle,
  Info,
  List,
  Image,
  FileText,
  LayoutDashboard,
  Loader2,
  Play,
} from "lucide-react";

// ── Types ──────────────────────────────────────────────────────

export interface A2UICardData {
  card_id: string;
  card_type: string;
  title: string;
  data: Record<string, unknown>;
  actions: A2UIAction[];
  metadata?: Record<string, unknown>;
}

export interface A2UIAction {
  id: string;
  label: string;
  action_type: string;
  payload?: Record<string, unknown>;
}

interface FormField {
  name: string;
  label: string;
  type: string;
  required?: boolean;
  default?: unknown;
  options?: string[];
  placeholder?: string;
}

interface A2UIRendererProps {
  card: A2UICardData;
  onAction?: (actionId: string, payload: Record<string, unknown>) => void;
}

// ── Card Wrapper ───────────────────────────────────────────────

function CardShell({
  icon,
  title,
  children,
  className = "",
}: {
  icon?: React.ReactNode;
  title?: string;
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 6, scale: 0.98 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      transition={{ duration: 0.2 }}
      className={`rounded-xl border border-border/20 bg-muted/10 overflow-hidden ${className}`}
    >
      {(icon || title) && (
        <div className="flex items-center gap-2 px-3 py-2 border-b border-border/10 bg-muted/5">
          {icon}
          {title && (
            <span className="text-[11px] font-medium text-foreground/70">
              {title}
            </span>
          )}
        </div>
      )}
      <div className="p-3">{children}</div>
    </motion.div>
  );
}

// ── Type Guards ──────────────────────────────────────────────

function isFormFieldArray(value: unknown): value is FormField[] {
  return Array.isArray(value) && value.every(
    (item) => typeof item === "object" && item !== null && "name" in item && "type" in item
  );
}

function isChartData(value: unknown): value is { labels: string[]; values: number[] } {
  return typeof value === "object" && value !== null && "labels" in value && "values" in value;
}

function isTableRows(value: unknown): value is Record<string, unknown>[] {
  return Array.isArray(value) && value.every((item) => typeof item === "object" && item !== null);
}

// ── Form Card ──────────────────────────────────────────────────

function FormCard({
  card,
  onAction,
}: {
  card: A2UICardData;
  onAction?: (id: string, payload: Record<string, unknown>) => void;
}) {
  const fields = isFormFieldArray(card.data.fields) ? card.data.fields : [];
  const [values, setValues] = useState<Record<string, unknown>>(() => {
    const init: Record<string, unknown> = {};
    for (const f of fields) {
      init[f.name] = f.default ?? "";
    }
    return init;
  });
  const [submitting, setSubmitting] = useState(false);

  const handleSubmit = useCallback(async () => {
    setSubmitting(true);
    try {
      await onAction?.("submit", values);
    } finally {
      setSubmitting(false);
    }
  }, [values, onAction]);

  return (
    <CardShell
      icon={<FormInput size={12} className="text-blue-400" />}
      title={card.title}
    >
      <div className="space-y-2">
        {fields.map((field) => (
          <div key={field.name} className="space-y-1">
            <label className="text-[10px] font-medium text-foreground/70">
              {field.label}
              {field.required && (
                <span className="text-red-400 ml-0.5">*</span>
              )}
            </label>
            {field.type === "textarea" ? (
              <Textarea
                placeholder={field.placeholder}
                value={String(values[field.name] ?? "")}
                onChange={(e) =>
                  setValues((prev) => ({ ...prev, [field.name]: e.target.value }))
                }
                className="text-[11px] min-h-[60px]"
              />
            ) : field.type === "select" ? (
              <Select
                value={String(values[field.name] ?? "")}
                onValueChange={(v) =>
                  setValues((prev) => ({ ...prev, [field.name]: v }))
                }
              >
                <SelectTrigger className="h-7 text-[11px]">
                  <SelectValue placeholder={field.placeholder || "Select..."} />
                </SelectTrigger>
                <SelectContent>
                  {(field.options ?? []).map((opt) => (
                    <SelectItem key={opt} value={opt} className="text-[11px]">
                      {opt}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            ) : field.type === "checkbox" ? (
              <div className="flex items-center gap-2">
                <Checkbox
                  checked={!!values[field.name]}
                  onCheckedChange={(v) =>
                    setValues((prev) => ({ ...prev, [field.name]: v }))
                  }
                />
                <span className="text-[10px]">{field.placeholder}</span>
              </div>
            ) : (
              <Input
                type={field.type === "number" ? "number" : "text"}
                placeholder={field.placeholder}
                value={String(values[field.name] ?? "")}
                onChange={(e) =>
                  setValues((prev) => ({ ...prev, [field.name]: e.target.value }))
                }
                className="h-7 text-[11px]"
              />
            )}
          </div>
        ))}
        <div className="flex gap-2 pt-1">
          {card.actions.map((action) => (
            <Button
              key={action.id}
              size="sm"
              className="h-6 text-[10px]"
              onClick={handleSubmit}
              disabled={submitting}
            >
              {submitting && (
                <Loader2 size={10} className="mr-1 animate-spin" />
              )}
              {action.label}
            </Button>
          ))}
        </div>
      </div>
    </CardShell>
  );
}

// ── Chart Card ─────────────────────────────────────────────────

function ChartCard({ card }: { card: A2UICardData }) {
  const chartType = typeof card.data.chart_type === "string" ? card.data.chart_type : "bar";
  const labels = Array.isArray(card.data.labels) ? card.data.labels.map(String) : [];
  const datasets = Array.isArray(card.data.datasets)
    ? card.data.datasets.filter(
        (ds): ds is { label: string; data: number[] } =>
          typeof ds === "object" && ds !== null && "label" in ds && "data" in ds
      )
    : [];

  // Simple bar chart using CSS
  const allValues = datasets.flatMap((d) => d.data);
  const maxVal = Math.max(...allValues, 1);

  return (
    <CardShell
      icon={<BarChart3 size={12} className="text-emerald-400" />}
      title={card.title}
    >
      <div className="space-y-2">
        {/* Legend */}
        {datasets.length > 1 && (
          <div className="flex gap-2 flex-wrap">
            {datasets.map((ds, i) => (
              <div key={i} className="flex items-center gap-1">
                <div
                  className="w-2 h-2 rounded-full"
                  style={{
                    backgroundColor: `hsl(${(i * 60) % 360}, 70%, 50%)`,
                  }}
                />
                <span className="text-[9px] text-muted-foreground">
                  {ds.label}
                </span>
              </div>
            ))}
          </div>
        )}

        {/* Bar chart */}
        {chartType === "bar" && (
          <div className="flex items-end gap-1 h-24">
            {labels.map((label, i) => (
              <div key={i} className="flex-1 flex flex-col items-center gap-0.5">
                <div className="w-full flex flex-col items-center">
                  {datasets.map((ds, di) => (
                    <div
                      key={di}
                      className="w-full rounded-t"
                      style={{
                        height: `${(ds.data[i] / maxVal) * 80}px`,
                        backgroundColor: `hsl(${(di * 60) % 360}, 70%, 50%)`,
                        opacity: 0.8,
                      }}
                    />
                  ))}
                </div>
                <span className="text-[7px] text-muted-foreground truncate w-full text-center">
                  {label}
                </span>
              </div>
            ))}
          </div>
        )}

        {/* Line chart (simplified) */}
        {chartType === "line" && (
          <svg viewBox="0 0 200 60" className="w-full h-16">
            {datasets.map((ds, di) => {
              const points = ds.data
                .map((v, i) => {
                  const x = (i / Math.max(ds.data.length - 1, 1)) * 200;
                  const y = 60 - (v / maxVal) * 55;
                  return `${x},${y}`;
                })
                .join(" ");
              return (
                <polyline
                  key={di}
                  points={points}
                  fill="none"
                  stroke={`hsl(${(di * 60) % 360}, 70%, 50%)`}
                  strokeWidth="1.5"
                  vectorEffect="non-scaling-stroke"
                />
              );
            })}
          </svg>
        )}

        {/* Pie chart (simplified — shows as horizontal bars) */}
        {chartType === "pie" && (
          <div className="space-y-1">
            {labels.map((label, i) => {
              const val = datasets[0]?.data[i] ?? 0;
              const pct = (val / maxVal) * 100;
              return (
                <div key={i} className="flex items-center gap-2">
                  <span className="text-[9px] w-12 truncate">{label}</span>
                  <div className="flex-1 h-2 bg-muted/20 rounded-full overflow-hidden">
                    <div
                      className="h-full rounded-full"
                      style={{
                        width: `${pct}%`,
                        backgroundColor: `hsl(${(i * 45) % 360}, 70%, 50%)`,
                      }}
                    />
                  </div>
                  <span className="text-[8px] text-muted-foreground w-8 text-right">
                    {val}
                  </span>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </CardShell>
  );
}

// ── Table Card ─────────────────────────────────────────────────

function TableCard({ card }: { card: A2UICardData }) {
  const columns = Array.isArray(card.data.columns) ? card.data.columns.map(String) : [];
  const rows = Array.isArray(card.data.rows)
    ? card.data.rows.filter((r): r is unknown[] => Array.isArray(r))
    : [];

  return (
    <CardShell
      icon={<Table2 size={12} className="text-cyan-400" />}
      title={card.title}
    >
      <div className="overflow-x-auto">
        <table className="w-full text-[10px]">
          <thead>
            <tr className="border-b border-border/10">
              {columns.map((col, i) => (
                <th
                  key={i}
                  className="text-left py-1 px-2 font-medium text-muted-foreground"
                >
                  {col}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map((row, ri) => (
              <tr
                key={ri}
                className="border-b border-border/5 hover:bg-muted/10"
              >
                {row.map((cell, ci) => (
                  <td key={ci} className="py-1 px-2">
                    {String(cell ?? "")}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </CardShell>
  );
}

// ── Alert Card ─────────────────────────────────────────────────

function AlertCard({ card }: { card: A2UICardData }) {
  const level = typeof card.data.level === "string" ? card.data.level : "info";
  const message = typeof card.data.message === "string" ? card.data.message : "";

  const levelConfig: Record<string, { icon: React.ReactNode; color: string }> = {
    info: { icon: <Info size={12} />, color: "text-blue-400 border-blue-500/20 bg-blue-500/10" },
    success: { icon: <CheckCircle size={12} />, color: "text-emerald-400 border-emerald-500/20 bg-emerald-500/10" },
    warning: { icon: <AlertTriangle size={12} />, color: "text-amber-400 border-amber-500/20 bg-amber-500/10" },
    error: { icon: <AlertCircle size={12} />, color: "text-red-400 border-red-500/20 bg-red-500/10" },
  };

  const config = levelConfig[level] ?? levelConfig.info;

  return (
    <div className={`rounded-lg border p-2.5 ${config.color}`}>
      <div className="flex items-center gap-2">
        {config.icon}
        <span className="text-[11px] font-medium">{card.title}</span>
      </div>
      <p className="text-[10px] mt-1 opacity-80">{message}</p>
    </div>
  );
}

// ── Progress Card ──────────────────────────────────────────────

function ProgressCard({ card }: { card: A2UICardData }) {
  const current = (card.data.current as number) ?? 0;
  const total = (card.data.total as number) ?? 100;
  const percentage = (card.data.percentage as number) ?? (current / total) * 100;
  const message = (card.data.message as string) ?? "";

  return (
    <CardShell
      icon={<Loader2 size={12} className="text-amber-400 animate-spin" />}
      title={card.title}
    >
      <div className="space-y-1.5">
        <div className="flex items-center justify-between">
          <span className="text-[10px] text-foreground/70">{message}</span>
          <span className="text-[10px] font-mono text-foreground/50">
            {current}/{total}
          </span>
        </div>
        <div className="w-full h-1.5 bg-muted/20 rounded-full overflow-hidden">
          <motion.div
            initial={{ width: 0 }}
            animate={{ width: `${percentage}%` }}
            transition={{ duration: 0.5 }}
            className="h-full bg-emerald-500 rounded-full"
          />
        </div>
        <span className="text-[9px] text-muted-foreground">
          {percentage.toFixed(1)}%
        </span>
      </div>
    </CardShell>
  );
}

// ── Code Card ──────────────────────────────────────────────────

function CodeCard({ card }: { card: A2UICardData }) {
  const code = (card.data.code as string) ?? "";
  const language = (card.data.language as string) ?? "text";

  return (
    <CardShell
      icon={<FileCode size={12} className="text-violet-400" />}
      title={card.title}
    >
      <pre className="text-[10px] font-mono bg-muted/20 rounded-lg p-2 overflow-x-auto max-h-48">
        <code>{code}</code>
      </pre>
      <div className="flex items-center gap-2 mt-1.5">
        <Badge variant="outline" className="text-[7px] h-3.5 px-1">
          {language}
        </Badge>
        <span className="text-[8px] text-muted-foreground">
          {code.split("\n").length} lines
        </span>
      </div>
    </CardShell>
  );
}

// ── Markdown Card ──────────────────────────────────────────────

function MarkdownCard({ card }: { card: A2UICardData }) {
  const content = (card.data.content as string) ?? "";
  return (
    <CardShell
      icon={<FileText size={12} className="text-foreground/50" />}
      title={card.title}
    >
      <div className="text-[11px] text-foreground/80 whitespace-pre-wrap max-h-48 overflow-y-auto">
        {content}
      </div>
    </CardShell>
  );
}

// ── Button Group Card ──────────────────────────────────────────

function ButtonGroupCard({
  card,
  onAction,
}: {
  card: A2UICardData;
  onAction?: (id: string, payload: Record<string, unknown>) => void;
}) {
  return (
    <CardShell title={card.title}>
      <div className="flex gap-2 flex-wrap">
        {card.actions.map((action) => {
          const style = (action.payload?.style as string) ?? "primary";
          return (
            <Button
              key={action.id}
              variant={style === "outline" ? "outline" : style === "danger" ? "destructive" : "default"}
              size="sm"
              className="h-6 text-[10px]"
              onClick={() => onAction?.(action.id, action.payload ?? {})}
            >
              {action.label}
            </Button>
          );
        })}
      </div>
    </CardShell>
  );
}

// ── Main Renderer ──────────────────────────────────────────────

export function A2UIRenderer({ card, onAction }: A2UIRendererProps) {
  switch (card.card_type) {
    case "form":
      return <FormCard card={card} onAction={onAction} />;
    case "chart":
      return <ChartCard card={card} />;
    case "table":
      return <TableCard card={card} />;
    case "alert":
      return <AlertCard card={card} />;
    case "progress":
      return <ProgressCard card={card} />;
    case "code":
      return <CodeCard card={card} />;
    case "markdown":
      return <MarkdownCard card={card} />;
    case "button":
      return <ButtonGroupCard card={card} onAction={onAction} />;
    default:
      return (
        <CardShell title={card.title}>
          <pre className="text-[9px] font-mono text-muted-foreground max-h-32 overflow-auto">
            {JSON.stringify(card.data, null, 2)}
          </pre>
        </CardShell>
      );
  }
}
