"""A2UI — Agent-to-UI dynamic card generation system.

Allows agents to generate rich UI cards (forms, charts, tables, etc.)
that render inside chat messages or as standalone panels.
"""

from __future__ import annotations

import logging
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Literal

logger = logging.getLogger(__name__)


class CardType(str, Enum):
    """Types of A2UI cards an agent can generate."""
    FORM = "form"
    CHART = "chart"
    TABLE = "table"
    BUTTON = "button"
    CARD = "card"
    DASHBOARD = "dashboard"
    CODE = "code"
    FILE_DIFF = "file_diff"
    PROGRESS = "progress"
    ALERT = "alert"
    LIST = "list"
    IMAGE = "image"
    MARKDOWN = "markdown"


class ChartType(str, Enum):
    LINE = "line"
    BAR = "bar"
    PIE = "pie"
    AREA = "area"
    SCATTER = "scatter"


class AlertLevel(str, Enum):
    INFO = "info"
    SUCCESS = "success"
    WARNING = "warning"
    ERROR = "error"


@dataclass(frozen=True)
class UIAction:
    """An interactive action on a card."""
    id: str
    label: str
    action_type: str  # "submit", "click", "navigate", "callback"
    payload: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class FormField:
    """A field in a dynamic form."""
    name: str
    label: str
    field_type: str  # "text", "number", "select", "checkbox", "textarea", "date"
    required: bool = False
    default: Any = None
    options: tuple[str, ...] = ()
    placeholder: str = ""


@dataclass
class A2UICard:
    """A dynamic UI card generated by an agent."""
    card_id: str
    card_type: CardType
    title: str = ""
    data: dict[str, Any] = field(default_factory=dict)
    actions: list[UIAction] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "card_id": self.card_id,
            "card_type": self.card_type.value,
            "title": self.title,
            "data": self.data,
            "actions": [
                {
                    "id": a.id,
                    "label": a.label,
                    "action_type": a.action_type,
                    "payload": a.payload,
                }
                for a in self.actions
            ],
            "metadata": self.metadata,
        }


class A2UIBuilder:
    """Fluent builder for A2UI cards."""

    def __init__(self, card_type: CardType, title: str = "") -> None:
        self._card = A2UICard(
            card_id=str(uuid.uuid4())[:8],
            card_type=card_type,
            title=title,
        )

    def with_data(self, key: str, value: Any) -> "A2UIBuilder":
        self._card.data[key] = value
        return self

    def with_action(self, action: UIAction) -> "A2UIBuilder":
        self._card.actions.append(action)
        return self

    def with_metadata(self, key: str, value: Any) -> "A2UIBuilder":
        self._card.metadata[key] = value
        return self

    def build(self) -> A2UICard:
        return self._card


class A2UIFactory:
    """Factory methods for common card types."""

    @staticmethod
    def form(title: str, fields: list[FormField], submit_label: str = "Submit") -> A2UICard:
        return (
            A2UIBuilder(CardType.FORM, title)
            .with_data("fields", [
                {
                    "name": f.name,
                    "label": f.label,
                    "type": f.field_type,
                    "required": f.required,
                    "default": f.default,
                    "options": list(f.options),
                    "placeholder": f.placeholder,
                }
                for f in fields
            ])
            .with_action(UIAction(id="submit", label=submit_label, action_type="submit"))
            .build()
        )

    @staticmethod
    def chart(title: str, chart_type: ChartType, labels: list[str], datasets: list[dict[str, Any]]) -> A2UICard:
        return (
            A2UIBuilder(CardType.CHART, title)
            .with_data("chart_type", chart_type.value)
            .with_data("labels", labels)
            .with_data("datasets", datasets)
            .build()
        )

    @staticmethod
    def table(title: str, columns: list[str], rows: list[list[Any]]) -> A2UICard:
        return (
            A2UIBuilder(CardType.TABLE, title)
            .with_data("columns", columns)
            .with_data("rows", rows)
            .build()
        )

    @staticmethod
    def alert(title: str, message: str, level: AlertLevel = AlertLevel.INFO) -> A2UICard:
        return (
            A2UIBuilder(CardType.ALERT, title)
            .with_data("message", message)
            .with_data("level", level.value)
            .build()
        )

    @staticmethod
    def code(title: str, code: str, language: str = "python") -> A2UICard:
        return (
            A2UIBuilder(CardType.CODE, title)
            .with_data("code", code)
            .with_data("language", language)
            .build()
        )

    @staticmethod
    def progress(title: str, current: int, total: int, message: str = "") -> A2UICard:
        return (
            A2UIBuilder(CardType.PROGRESS, title)
            .with_data("current", current)
            .with_data("total", total)
            .with_data("percentage", round(current / max(total, 1) * 100, 1))
            .with_data("message", message)
            .build()
        )

    @staticmethod
    def file_diff(title: str, file_path: str, old_content: str, new_content: str) -> A2UICard:
        return (
            A2UIBuilder(CardType.FILE_DIFF, title)
            .with_data("file_path", file_path)
            .with_data("old_content", old_content)
            .with_data("new_content", new_content)
            .build()
        )

    @staticmethod
    def markdown(title: str, content: str) -> A2UICard:
        return (
            A2UIBuilder(CardType.MARKDOWN, title)
            .with_data("content", content)
            .build()
        )

    @staticmethod
    def list_card(title: str, items: list[dict[str, Any]], ordered: bool = False) -> A2UICard:
        return (
            A2UIBuilder(CardType.LIST, title)
            .with_data("items", items)
            .with_data("ordered", ordered)
            .build()
        )

    @staticmethod
    def button_group(title: str, buttons: list[dict[str, str]]) -> A2UICard:
        """buttons: [{"label": "...", "action_id": "...", "style": "primary|danger|outline"}]"""
        card = A2UIBuilder(CardType.BUTTON, title).build()
        for btn in buttons:
            card.actions.append(UIAction(
                id=btn.get("action_id", str(uuid.uuid4())[:8]),
                label=btn.get("label", ""),
                action_type="click",
                payload={"style": btn.get("style", "primary")},
            ))
        return card

    @staticmethod
    def dashboard(title: str, metrics: list[dict[str, Any]]) -> A2UICard:
        """metrics: [{"label": "...", "value": "...", "icon": "...", "trend": "up|down|flat"}]"""
        return (
            A2UIBuilder(CardType.DASHBOARD, title)
            .with_data("metrics", metrics)
            .build()
        )


# ── Card Registry (for action routing) ─────────────────────────

class A2UIRegistry:
    """Registry for handling A2UI card actions."""

    def __init__(self) -> None:
        self._handlers: dict[str, Any] = {}

    def register_handler(self, action_id: str, handler: Any) -> None:
        self._handlers[action_id] = handler

    def get_handler(self, action_id: str) -> Any | None:
        return self._handlers.get(action_id)

    async def handle_action(self, action_id: str, payload: dict[str, Any]) -> dict[str, Any]:
        handler = self._handlers.get(action_id)
        if handler is None:
            return {"error": f"No handler for action: {action_id}"}
        try:
            if callable(handler):
                result = handler(payload)
                if hasattr(result, "__await__"):
                    result = await result
                return {"success": True, "result": result}
            return {"success": True}
        except Exception as exc:
            return {"error": str(exc)}


# Module-level singletons
_registry: A2UIRegistry | None = None


def get_a2ui_registry() -> A2UIRegistry:
    global _registry
    if _registry is None:
        _registry = A2UIRegistry()
    return _registry
