"""
NEXUS Watchdog Service — Automated monitoring and summarization of information sources.

Supports:
  - RSS feed monitoring and parsing
  - Web page change detection
  - Periodic search and alert
  - Source deduplication
  - Summary generation using LLM
  - Schedule management (cron-like)
  - Integration with the memory service for storing results
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import logging
import re
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Callable, Optional
from urllib.parse import urlparse

import httpx

from nexus.core.config import get_settings

logger = logging.getLogger(__name__)


class SourceType(str, Enum):
    """Types of monitored sources."""
    RSS = "rss"
    WEB_PAGE = "web_page"
    SEARCH = "search"


class MonitorStatus(str, Enum):
    """Status of a monitor."""
    ACTIVE = "active"
    PAUSED = "paused"
    ERROR = "error"
    STOPPED = "stopped"


@dataclass
class RSSItem:
    """A single RSS feed item."""
    title: str
    link: str
    description: str = ""
    published: str = ""
    author: str = ""
    guid: str = ""
    content_hash: str = ""

    def compute_hash(self) -> str:
        """Compute content hash for deduplication."""
        content = f"{self.title}|{self.link}|{self.description}"
        self.content_hash = hashlib.sha256(content.encode()).hexdigest()[:16]
        return self.content_hash


@dataclass
class WebPageSnapshot:
    """Snapshot of a web page for change detection."""
    url: str
    content_hash: str = ""
    content_length: int = 0
    title: str = ""
    timestamp: float = 0.0
    status_code: int = 0

    def compute_hash(self, content: str) -> str:
        """Compute content hash."""
        self.content_hash = hashlib.sha256(content.encode()).hexdigest()[:16]
        self.content_length = len(content)
        self.timestamp = time.time()
        return self.content_hash


@dataclass
class WatchdogSource:
    """A monitored information source."""
    source_id: str
    name: str
    source_type: SourceType
    url: str
    schedule: str = "0 * * * *"  # cron-like: default every hour
    query: str = ""  # For search sources
    keywords: list[str] = field(default_factory=list)
    max_items: int = 10
    status: MonitorStatus = MonitorStatus.ACTIVE
    last_checked: float = 0.0
    last_error: str = ""
    check_count: int = 0
    seen_hashes: set[str] = field(default_factory=set)

    def to_dict(self) -> dict[str, Any]:
        return {
            "source_id": self.source_id,
            "name": self.name,
            "source_type": self.source_type.value,
            "url": self.url,
            "schedule": self.schedule,
            "query": self.query,
            "keywords": self.keywords,
            "max_items": self.max_items,
            "status": self.status.value,
            "last_checked": self.last_checked,
            "check_count": self.check_count,
            "seen_hashes": list(self.seen_hashes),
        }


@dataclass
class WatchdogAlert:
    """An alert generated by the watchdog."""
    source_id: str
    source_name: str
    alert_type: str  # "new_item", "page_changed", "search_hit"
    title: str
    content: str
    url: str = ""
    timestamp: float = 0.0
    summary: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "source_id": self.source_id,
            "source_name": self.source_name,
            "alert_type": self.alert_type,
            "title": self.title,
            "url": self.url,
            "timestamp": self.timestamp,
            "summary": self.summary,
        }


@dataclass
class CronSchedule:
    """Simple cron-like schedule parser."""
    minute: str = "0"
    hour: str = "*"
    day_of_month: str = "*"
    month: str = "*"
    day_of_week: str = "*"

    @classmethod
    def parse(cls, expression: str) -> CronSchedule:
        """Parse a cron expression into a CronSchedule."""
        parts = expression.strip().split()
        if len(parts) != 5:
            raise ValueError(f"Invalid cron expression (expected 5 fields): {expression}")
        return cls(
            minute=parts[0],
            hour=parts[1],
            day_of_month=parts[2],
            month=parts[3],
            day_of_week=parts[4],
        )

    def should_run(self, current_time: Optional[float] = None) -> bool:
        """
        Check if the schedule should trigger at the given time.

        Simple check: compares against the current minute/hour/etc.
        Supports '*' (any) and specific values.
        """
        import datetime

        now = datetime.datetime.fromtimestamp(current_time or time.time())

        def matches(cron_field: str, value: int) -> bool:
            if cron_field == "*":
                return True
            try:
                return int(cron_field) == value
            except ValueError:
                return True  # Complex expressions: be permissive

        return (
            matches(self.minute, now.minute)
            and matches(self.hour, now.hour)
            and matches(self.day_of_month, now.day)
            and matches(self.month, now.month)
            and matches(self.day_of_week, now.weekday())
        )


class WatchdogService:
    """
    Automated monitoring and summarization service.

    Monitors RSS feeds, web pages, and search queries on a
    configurable schedule, generates alerts for new content,
    deduplicates results, and produces summaries using LLM.

    Usage:
        watchdog = WatchdogService()

        # Add sources
        watchdog.add_rss_source("tech-news", "Tech News", "https://example.com/feed.xml")
        watchdog.add_web_source("my-site", "My Site", "https://example.com")

        # Start monitoring
        await watchdog.start()

        # Check for alerts
        alerts = watchdog.get_pending_alerts()
    """

    def __init__(self, memory_service=None):
        """
        Initialize the WatchdogService.

        Args:
            memory_service: Optional NexusMemoryService for storing results.
                           If provided, alerts and summaries are automatically stored.
        """
        self.settings = get_settings()
        self._memory_service = memory_service
        self._sources: dict[str, WatchdogSource] = {}
        self._alerts: list[WatchdogAlert] = []
        self._page_snapshots: dict[str, WebPageSnapshot] = {}
        self._running = False
        self._task: Optional[asyncio.Task] = None
        self._callbacks: list[Callable] = []
        self._router = None

    def _get_router(self):
        """Lazily initialize the LLM router."""
        if self._router is None:
            from nexus.llm.router import LLMRouter
            self._router = LLMRouter()
        return self._router

    # ── Source Management ────────────────────────────────────────────

    def add_rss_source(
        self,
        source_id: str,
        name: str,
        url: str,
        schedule: str = "0 * * * *",
        keywords: Optional[list[str]] = None,
        max_items: int = 10,
    ) -> WatchdogSource:
        """
        Add an RSS feed source to monitor.

        Args:
            source_id: Unique identifier for the source.
            name: Human-readable name.
            url: RSS feed URL.
            schedule: Cron-like schedule (default: every hour).
            keywords: Optional keywords to filter items.
            max_items: Maximum items to process per check.

        Returns:
            The created WatchdogSource.
        """
        source = WatchdogSource(
            source_id=source_id,
            name=name,
            source_type=SourceType.RSS,
            url=url,
            schedule=schedule,
            keywords=keywords or [],
            max_items=max_items,
        )
        self._sources[source_id] = source
        logger.info("Added RSS source: %s (%s)", name, url)
        return source

    def add_web_source(
        self,
        source_id: str,
        name: str,
        url: str,
        schedule: str = "0 */6 * * *",
        keywords: Optional[list[str]] = None,
    ) -> WatchdogSource:
        """
        Add a web page source to monitor for changes.

        Args:
            source_id: Unique identifier for the source.
            name: Human-readable name.
            url: Web page URL.
            schedule: Cron-like schedule (default: every 6 hours).
            keywords: Optional keywords to detect relevant changes.

        Returns:
            The created WatchdogSource.
        """
        source = WatchdogSource(
            source_id=source_id,
            name=name,
            source_type=SourceType.WEB_PAGE,
            url=url,
            schedule=schedule,
            keywords=keywords or [],
        )
        self._sources[source_id] = source
        logger.info("Added web page source: %s (%s)", name, url)
        return source

    def add_search_source(
        self,
        source_id: str,
        name: str,
        query: str,
        schedule: str = "0 9 * * *",
        keywords: Optional[list[str]] = None,
    ) -> WatchdogSource:
        """
        Add a periodic search source.

        Args:
            source_id: Unique identifier for the source.
            name: Human-readable name.
            query: Search query to execute periodically.
            schedule: Cron-like schedule (default: daily at 9am).
            keywords: Optional additional keywords.

        Returns:
            The created WatchdogSource.
        """
        source = WatchdogSource(
            source_id=source_id,
            name=name,
            source_type=SourceType.SEARCH,
            url="",
            query=query,
            schedule=schedule,
            keywords=keywords or [],
        )
        self._sources[source_id] = source
        logger.info("Added search source: %s (query: %s)", name, query[:50])
        return source

    def remove_source(self, source_id: str) -> bool:
        """Remove a monitored source."""
        source = self._sources.pop(source_id, None)
        if source:
            logger.info("Removed source: %s", source_id)
            return True
        return False

    def pause_source(self, source_id: str) -> bool:
        """Pause monitoring of a source."""
        source = self._sources.get(source_id)
        if source:
            source.status = MonitorStatus.PAUSED
            return True
        return False

    def resume_source(self, source_id: str) -> bool:
        """Resume monitoring of a paused source."""
        source = self._sources.get(source_id)
        if source:
            source.status = MonitorStatus.ACTIVE
            return True
        return False

    def list_sources(self) -> list[dict[str, Any]]:
        """List all monitored sources."""
        return [source.to_dict() for source in self._sources.values()]

    def get_source(self, source_id: str) -> Optional[dict[str, Any]]:
        """Get details of a specific source."""
        source = self._sources.get(source_id)
        return source.to_dict() if source else None

    # ── Alert Management ─────────────────────────────────────────────

    def get_pending_alerts(self, limit: int = 50) -> list[dict[str, Any]]:
        """Get pending (unprocessed) alerts."""
        return [alert.to_dict() for alert in self._alerts[-limit:]]

    def clear_alerts(self):
        """Clear all pending alerts."""
        self._alerts.clear()

    def add_callback(self, callback: Callable):
        """Add a callback function to be called when new alerts are generated."""
        self._callbacks.append(callback)

    async def _notify_callbacks(self, alerts: list[WatchdogAlert]):
        """Notify all registered callbacks about new alerts."""
        for callback in self._callbacks:
            try:
                result = callback(alerts)
                if asyncio.iscoroutine(result):
                    await result
            except Exception as e:
                logger.warning("Callback error: %s", e)

    # ── Monitoring Engine ────────────────────────────────────────────

    async def start(self, check_interval: int = 60):
        """
        Start the watchdog monitoring loop.

        Args:
            check_interval: Seconds between schedule checks.
        """
        if self._running:
            logger.warning("Watchdog already running")
            return

        self._running = True
        self._task = asyncio.create_task(self._monitor_loop(check_interval))
        logger.info("Watchdog service started (check interval: %ds)", check_interval)

    async def stop(self):
        """Stop the watchdog monitoring loop."""
        self._running = False
        if self._task:
            self._task.cancel()
            try:
                await self._task
            except asyncio.CancelledError:
                pass
            self._task = None
        logger.info("Watchdog service stopped")

    async def _monitor_loop(self, check_interval: int):
        """Main monitoring loop that checks schedules and runs sources."""
        while self._running:
            try:
                await self._check_all_sources()
            except Exception as e:
                logger.error("Monitor loop error: %s", e)

            await asyncio.sleep(check_interval)

    async def _check_all_sources(self):
        """Check all active sources against their schedules."""
        now = time.time()

        for source in self._sources.values():
            if source.status != MonitorStatus.ACTIVE:
                continue

            try:
                schedule = CronSchedule.parse(source.schedule)
                if schedule.should_run(now):
                    await self._check_source(source)
            except Exception as e:
                logger.error(
                    "Error checking source %s: %s", source.source_id, e,
                )
                source.status = MonitorStatus.ERROR
                source.last_error = str(e)

    async def _check_source(self, source: WatchdogSource):
        """Check a single source for new content."""
        logger.debug("Checking source: %s (%s)", source.name, source.source_type.value)
        source.check_count += 1
        source.last_checked = time.time()

        new_alerts: list[WatchdogAlert] = []

        try:
            if source.source_type == SourceType.RSS:
                new_alerts = await self._check_rss(source)
            elif source.source_type == SourceType.WEB_PAGE:
                new_alerts = await self._check_web_page(source)
            elif source.source_type == SourceType.SEARCH:
                new_alerts = await self._check_search(source)
        except Exception as e:
            logger.error("Source check failed for %s: %s", source.source_id, e)
            source.last_error = str(e)
            source.status = MonitorStatus.ERROR
            return

        if new_alerts:
            # Generate summaries using LLM
            if len(new_alerts) > 1:
                await self._summarize_alerts(new_alerts)
            else:
                await self._summarize_alert(new_alerts[0])

            # Store in memory service if available
            if self._memory_service:
                await self._store_alerts(new_alerts)

            # Add to pending alerts
            self._alerts.extend(new_alerts)

            # Notify callbacks
            await self._notify_callbacks(new_alerts)

            logger.info(
                "Source %s: %d new alert(s)", source.source_id, len(new_alerts),
            )
        else:
            logger.debug("Source %s: no new content", source.source_id)

    async def _check_rss(self, source: WatchdogSource) -> list[WatchdogAlert]:
        """Check an RSS feed for new items."""
        items = await self._fetch_rss(source.url)
        alerts: list[WatchdogAlert] = []

        for item in items[:source.max_items]:
            content_hash = item.compute_hash()

            # Deduplication
            if content_hash in source.seen_hashes:
                continue

            source.seen_hashes.add(content_hash)

            # Keyword filtering
            if source.keywords:
                text = f"{item.title} {item.description}".lower()
                if not any(kw.lower() in text for kw in source.keywords):
                    continue

            alerts.append(WatchdogAlert(
                source_id=source.source_id,
                source_name=source.name,
                alert_type="new_item",
                title=item.title,
                content=item.description[:2000],
                url=item.link,
                timestamp=time.time(),
            ))

        return alerts

    async def _check_web_page(self, source: WatchdogSource) -> list[WatchdogAlert]:
        """Check a web page for changes."""
        try:
            async with httpx.AsyncClient(timeout=15.0, follow_redirects=True) as client:
                response = await client.get(
                    source.url,
                    headers={"User-Agent": "NEXUS-Watchdog/1.0"},
                )

            if response.status_code != 200:
                logger.warning(
                    "Web page check failed for %s: HTTP %d",
                    source.url, response.status_code,
                )
                return []

            content = response.text

            # Strip HTML for hash comparison
            text_content = re.sub(r"<[^>]+>", " ", content)
            text_content = re.sub(r"\s+", " ", text_content).strip()

            snapshot = WebPageSnapshot(
                url=source.url,
                status_code=response.status_code,
            )
            snapshot.compute_hash(text_content)

            # Extract title
            title_match = re.search(r"<title[^>]*>(.*?)</title>", content, re.IGNORECASE | re.DOTALL)
            if title_match:
                snapshot.title = title_match.group(1).strip()

            previous = self._page_snapshots.get(source.source_id)

            # Update snapshot
            self._page_snapshots[source.source_id] = snapshot

            # No previous snapshot — first check, no alert
            if not previous:
                return []

            # Compare content hashes
            if previous.content_hash != snapshot.content_hash:
                # Keyword filtering
                if source.keywords:
                    if not any(kw.lower() in text_content.lower() for kw in source.keywords):
                        return []

                return [WatchdogAlert(
                    source_id=source.source_id,
                    source_name=source.name,
                    alert_type="page_changed",
                    title=f"Change detected on {source.name}",
                    content=f"Content hash changed from {previous.content_hash} to {snapshot.content_hash}. "
                            f"Content length: {snapshot.content_length} chars.",
                    url=source.url,
                    timestamp=time.time(),
                )]

            return []

        except Exception as e:
            logger.error("Web page check error for %s: %s", source.url, e)
            return []

    async def _check_search(self, source: WatchdogSource) -> list[WatchdogAlert]:
        """Execute a periodic search and alert on new results."""
        try:
            from nexus.knowledge.web_search import MultiSourceWebSearch

            search = MultiSourceWebSearch()
            results = await search.search(source.query, num_results=source.max_items)
            alerts: list[WatchdogAlert] = []

            for result in results:
                # Deduplicate by URL
                content_hash = hashlib.sha256(result.url.encode()).hexdigest()[:16]
                if content_hash in source.seen_hashes:
                    continue

                source.seen_hashes.add(content_hash)

                # Keyword filtering
                if source.keywords:
                    text = f"{result.title} {result.snippet}".lower()
                    if not any(kw.lower() in text for kw in source.keywords):
                        continue

                alerts.append(WatchdogAlert(
                    source_id=source.source_id,
                    source_name=source.name,
                    alert_type="search_hit",
                    title=result.title,
                    content=result.snippet[:2000],
                    url=result.url,
                    timestamp=time.time(),
                ))

            return alerts

        except Exception as e:
            logger.error("Search check error for %s: %s", source.source_id, e)
            return []

    # ── RSS Parsing ──────────────────────────────────────────────────

    async def _fetch_rss(self, url: str) -> list[RSSItem]:
        """
        Fetch and parse an RSS feed.

        Uses basic XML parsing that works without external dependencies.
        For production, consider using feedparser.
        """
        try:
            async with httpx.AsyncClient(timeout=15.0, follow_redirects=True) as client:
                response = await client.get(
                    url,
                    headers={"User-Agent": "NEXUS-Watchdog/1.0"},
                )

            if response.status_code != 200:
                logger.warning("RSS fetch failed for %s: HTTP %d", url, response.status_code)
                return []

            return self._parse_rss_xml(response.text)

        except Exception as e:
            logger.error("RSS fetch error for %s: %s", url, e)
            return []

    def _parse_rss_xml(self, xml_content: str) -> list[RSSItem]:
        """Parse RSS XML content into RSSItem objects."""
        items: list[RSSItem] = []

        # Simple regex-based RSS parsing (no external XML parser needed)
        # Match <item>...</item> blocks
        item_pattern = re.compile(r"<item>(.*?)</item>", re.DOTALL | re.IGNORECASE)
        entry_pattern = re.compile(r"<entry>(.*?)</entry>", re.DOTALL | re.IGNORECASE)

        # Try RSS format first, then Atom
        for pattern in [item_pattern, entry_pattern]:
            for match in pattern.finditer(xml_content):
                block = match.group(1)

                # Extract fields
                def extract_tag(tag: str) -> str:
                    m = re.search(rf"<{tag}[^>]*>(.*?)</{tag}>", block, re.DOTALL | re.IGNORECASE)
                    if m:
                        text = m.group(1)
                        # Remove CDATA
                        text = re.sub(r"<!\[CDATA\[(.*?)\]\]>", r"\1", text, flags=re.DOTALL)
                        # Remove HTML tags
                        text = re.sub(r"<[^>]+>", "", text)
                        return text.strip()
                    return ""

                title = extract_tag("title")
                link = extract_tag("link")

                # Atom feeds use <link href="...">
                if not link:
                    link_match = re.search(r'<link[^>]+href="([^"]+)"', block, re.IGNORECASE)
                    if link_match:
                        link = link_match.group(1)

                description = extract_tag("description") or extract_tag("summary") or extract_tag("content")
                published = extract_tag("pubDate") or extract_tag("published") or extract_tag("updated")
                author = extract_tag("author") or extract_tag("dc:creator")
                guid = extract_tag("guid") or extract_tag("id")

                if title or link:
                    items.append(RSSItem(
                        title=title,
                        link=link,
                        description=description[:5000],
                        published=published,
                        author=author,
                        guid=guid or link,
                    ))

        return items

    # ── Summarization ────────────────────────────────────────────────

    async def _summarize_alerts(self, alerts: list[WatchdogAlert]):
        """Generate a combined summary for multiple alerts."""
        if not alerts:
            return

        # Build content for summarization
        contents = []
        for alert in alerts:
            contents.append(f"- [{alert.title}]({alert.url}): {alert.content[:500]}")

        combined = "\n".join(contents)

        try:
            router = self._get_router()
            from nexus.llm.router import TaskComplexity

            response = await router.complete(
                messages=[
                    {
                        "role": "system",
                        "content": (
                            "Summarize the following items concisely in 2-3 sentences. "
                            "Highlight the most important or relevant information."
                        ),
                    },
                    {"role": "user", "content": combined},
                ],
                task_complexity=TaskComplexity.SIMPLE,
                temperature=0.3,
                max_tokens=256,
            )

            summary = response.content.strip()
            for alert in alerts:
                alert.summary = summary

        except Exception as e:
            logger.warning("Failed to generate summary: %s", e)

    async def _summarize_alert(self, alert: WatchdogAlert):
        """Generate a summary for a single alert."""
        try:
            router = self._get_router()
            from nexus.llm.router import TaskComplexity

            response = await router.complete(
                messages=[
                    {
                        "role": "system",
                        "content": "Summarize this in one concise sentence.",
                    },
                    {
                        "role": "user",
                        "content": f"{alert.title}\n\n{alert.content[:1000]}",
                    },
                ],
                task_complexity=TaskComplexity.SIMPLE,
                temperature=0.3,
                max_tokens=128,
            )

            alert.summary = response.content.strip()

        except Exception as e:
            logger.warning("Failed to generate summary for alert: %s", e)

    # ── Memory Integration ───────────────────────────────────────────

    async def _store_alerts(self, alerts: list[WatchdogAlert]):
        """Store alerts in the memory service for later retrieval."""
        if not self._memory_service:
            return

        try:
            for alert in alerts:
                text = f"[{alert.alert_type}] {alert.title}"
                if alert.summary:
                    text += f"\nSummary: {alert.summary}"
                text += f"\nSource: {alert.source_name}"
                if alert.url:
                    text += f"\nURL: {alert.url}"
                text += f"\n\n{alert.content[:2000]}"

                await self._memory_service.store(
                    text=text,
                    namespace="knowledge",
                    metadata={
                        "source": "watchdog",
                        "source_id": alert.source_id,
                        "alert_type": alert.alert_type,
                        "url": alert.url,
                    },
                )
        except Exception as e:
            logger.error("Failed to store alerts in memory: %s", e)

    # ── Manual Check ─────────────────────────────────────────────────

    async def check_now(self, source_id: Optional[str] = None) -> list[dict[str, Any]]:
        """
        Manually trigger a check for one or all sources.

        Args:
            source_id: Optional specific source to check. If None, checks all.

        Returns:
            List of new alerts generated.
        """
        if source_id:
            source = self._sources.get(source_id)
            if not source:
                return []
            await self._check_source(source)
        else:
            await self._check_all_sources()

        # Return the most recent alerts
        recent = [a for a in self._alerts if time.time() - a.timestamp < 60]
        return [alert.to_dict() for alert in recent]
